### ISSUE TITLE
How do I remove the separator from the list

### ISSUE THREAD

**Issue by mejias1990** [CSolanaM/SkeletonUI#26]

**Comment by CSolanaM** [comment]
This is not a SkeletonUI's issue, since it only wraps the `List` component, so the behavior is the same as the usual one.

You can do some research, for example: https://stackoverflow.com/questions/56553672/how-to-remove-the-line-separators-from-a-list-in-swiftui-without-using-foreach

Closing.

PD: Please, try to fill your next issue following the provided template.
