### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by sakshibala-halodoc** [CSolanaM/SkeletonUI#53]
Subject: We need to incorporate the xcprivacy manifest into our app . Starting March 13, Apple will send notifications when uploading builds to the App Store, and this will become mandatory from May 1. All the SDKs used in our app needs to incorporate the xcprivacy manifest.
Reference: https://developer.apple.com/news/?id=3d8a9yyh

Actions needed: We need the compatible xcprivacy manifest version IOS SDK with xcprivacy manifest. We are expecting a seamless upgrade by upgrading to the latest version.

**Comment by CSolanaM** [comment]
Hi,

It doesn't use any file timestamps, UserDefaults, active keyboard, system boot time or disk space API's. That's why, honestly I don't think that SkeletonUI uses any of the mentioned set of API's. Anyway:

- Does the file need to be declared even if empty?
- Are you already getting a warning specifying which one of the API's are being used?

Thanks!
